### ISSUE TITLE
RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by Chuan1997** [guoyang9/BPR-pytorch#1]
how can I solve this problem?

**Comment by guoyang9** [comment]
Try to set the num_worker to be 0 for this [line](https://github.com/guoyang9/BPR-pytorch/blob/a21fbcde6ab85f5215fe0db9bdb9471116e1a667/main.py#L74).

**Comment by Chuan1997** [comment]
problem solved, thank you!
