### ISSUE TITLE
How to understand the log function in the loss calculation process and negative sample in every epoch?

### ISSUE THREAD

**Issue by July541** [guoyang9/BPR-pytorch#2]
Hello,
I have some trouble while understanding [this](https://github.com/guoyang9/BPR-pytorch/blob/master/main.py#L100) log function. It looks no obvious influence after removing this log Intuitively, but the experiment shows it really has about a 10% performance penalty. By increasing the number of epochs, it back to the origin line. I guess the log function may make the network convergence early. What is the difference between these two situations?

And, as I have poor knowledge about sampling, is it necessary to take a negative sample processing [in every epoch](https://github.com/guoyang9/BPR-pytorch/blob/master/main.py#L91)?

**Comment by guoyang9** [comment]
Q1: Log function does accelerating convergence, more explanation can be found at the BPR paper.
Q2: It is useful to avoid over-fitting.

**Comment by July541** [comment]
Thank you, it is my fault to ignore it.
