### ISSUE TITLE
你好，您的评测阶段好像有问题

### ISSUE THREAD

**Issue by syiswell** [guoyang9/BPR-pytorch#4]

**Comment by EsteroBlue** [comment]
应该是没有问题的，
![图片](https://user-images.githubusercontent.com/35621940/103868783-5b7af280-5097-11eb-9586-16930be43f35.png)
首先，如上图所示，每一行为一个user的test记录：（user, test item），括号里的是user与其将来会购买的item，括号后的为随机选取的neg sample item。且一行有100个item，您可以数数。
下面是metric里的解释，请看图片中的标注：
![图片](https://user-images.githubusercontent.com/35621940/103869242-0e4b5080-5098-11eb-8c98-06f033293435.png)

**Comment by syiswell** [comment]
非常感谢您的回答，是我疏忽了，未能考虑您的数据处理方式。不过建议你以后不要时间负采样测试哈，因为这种方法在2020年的KDD best paper上已经被证明对比于真实的指标有比较大的偏差。
